[extend]
useDefault = true

[allowlist]
description = "Ignorar arquivos de exemplo e fixtures de teste"
paths = [
  '''.env\.example''',
  '''test/.*\.ts''',
  '''test/helpers/.*\.ts''',
]
regexes = [
  '''change-me''',
]
