[extend]
useDefault = true

[allowlist]
description = "Ignorar arquivos de exemplo e fixtures de teste"
paths = [
  '''.env\.example''',
  '''test/.*\.ts''',
  '''test/helpers/.*\.ts''',
  '''__tests__/.*\.ts''',
  '''__tests__/.*\.tsx''',
  '''.*\.spec\.ts''',
  '''.*\.e2e-spec\.ts''',
]
regexes = [
  '''change-me''',
]
