/**
 * Catálogo canônico das rotas do menu (protótipo Layout.tsx → ALL_NAV_GROUPS; 39
 * rotas — AD-15 revogou as 2 entradas da AD-11).
 */
export const MENUS_CANONICOS = [
  '/comercial/clientes',
  '/comercial/pedidos',
  '/comercial/tabela-precos',
  '/comercial/disponibilidade',
  '/comercial/espelho',
  '/gestao/dashboard',
  '/gestao/operacoes',
  '/gestao/compras',
  '/gestao/overbooking',
  '/gestao/aprovacoes',
  '/gestao/relatorios',
  '/recebimento/recebimento-carga',
  '/recebimento/pesagem-destinacao',
  '/recebimento/etiquetas',
  '/desossa/dashboard',
  '/desossa/pesagem-destinacao',
  '/desossa/etiquetas',
  '/estoque/consulta',
  '/estoque/entrada-itens',
  '/estoque/ajustes',
  '/carga/planejamento',
  '/carga/conferencia',
  '/carga/enviar-faturamento',
  '/faturamento/pre-faturamento',
  '/faturamento/notas-xml',
  '/faturamento/seguro-manual',
  '/faturamento/liberacao',
  '/cadastros/representantes',
  '/cadastros/produtos',
  '/cadastros/fornecedores',
  '/cadastros/caminhoes',
  '/cadastros/motoristas',
  '/cadastros/rotas',
  '/cadastros/regras-transformacao',
  '/cadastros/modelos-etiqueta',
  '/admin/usuarios',
  '/admin/perfis',
  '/admin/parametros',
  '/admin/auditoria',
] as const;

export type MenuCanonico = (typeof MENUS_CANONICOS)[number];

const SET_MENUS = new Set<string>(MENUS_CANONICOS);

export function menusDesconhecidos(hrefs: string[]): string[] {
  return hrefs.filter((href) => !SET_MENUS.has(href));
}

/**
 * Menus visíveis por perfil — transcrição da coluna "Perfis RBAC" da matriz de
 * rastreabilidade v1.1 (linhas 3–41), invertida de rota→perfis para perfil→rotas.
 * Total: 126 pares perfil×rota. Alterar aqui exige alterar a matriz (decisão 7).
 */
export const MENUS_VISIVEIS_POR_PERFIL: Record<string, string[]> = {
  administrador: [...MENUS_CANONICOS],
  gestor: [
    '/comercial/clientes',
    '/comercial/pedidos',
    '/comercial/tabela-precos',
    '/comercial/disponibilidade',
    '/comercial/espelho',
    '/gestao/dashboard',
    '/gestao/operacoes',
    '/gestao/compras',
    '/gestao/overbooking',
    '/gestao/aprovacoes',
    '/gestao/relatorios',
    '/recebimento/recebimento-carga',
    '/recebimento/pesagem-destinacao',
    '/recebimento/etiquetas',
    '/desossa/dashboard',
    '/desossa/pesagem-destinacao',
    '/desossa/etiquetas',
    '/estoque/consulta',
    '/estoque/entrada-itens',
    '/estoque/ajustes',
    '/carga/planejamento',
    '/carga/conferencia',
    '/carga/enviar-faturamento',
    '/faturamento/pre-faturamento',
    '/faturamento/notas-xml',
    '/faturamento/seguro-manual',
    '/faturamento/liberacao',
    '/cadastros/representantes',
    '/cadastros/produtos',
    '/cadastros/fornecedores',
    '/cadastros/caminhoes',
    '/cadastros/motoristas',
    '/cadastros/rotas',
    '/cadastros/regras-transformacao',
    '/cadastros/modelos-etiqueta',
    '/admin/auditoria',
  ],
  compras: [
    '/gestao/operacoes',
    '/gestao/compras',
    '/gestao/overbooking',
    '/recebimento/recebimento-carga',
    '/cadastros/fornecedores',
  ],
  comercial: [
    '/comercial/clientes',
    '/comercial/pedidos',
    '/comercial/tabela-precos',
    '/comercial/disponibilidade',
    '/comercial/espelho',
    '/gestao/compras',
    '/gestao/overbooking',
    '/desossa/dashboard',
  ],
  recebimento_pesagem: [
    '/gestao/aprovacoes',
    '/recebimento/recebimento-carga',
    '/recebimento/pesagem-destinacao',
    '/recebimento/etiquetas',
    '/estoque/consulta',
    '/estoque/entrada-itens',
    '/estoque/ajustes',
  ],
  corte: ['/desossa/dashboard', '/desossa/pesagem-destinacao', '/desossa/etiquetas'],
  expedicao: [
    '/comercial/pedidos',
    '/comercial/espelho',
    '/estoque/consulta',
    '/estoque/entrada-itens',
    '/estoque/ajustes',
    '/carga/planejamento',
    '/carga/conferencia',
    '/carga/enviar-faturamento',
    '/cadastros/caminhoes',
    '/cadastros/motoristas',
  ],
  conferente: ['/carga/conferencia'],
  faturamento: [
    '/comercial/clientes',
    '/comercial/pedidos',
    '/gestao/relatorios',
    '/recebimento/recebimento-carga',
    '/faturamento/pre-faturamento',
    '/faturamento/notas-xml',
    '/faturamento/seguro-manual',
    '/faturamento/liberacao',
  ],
  logistica: ['/faturamento/notas-xml', '/faturamento/seguro-manual', '/faturamento/liberacao'],
  diretoria: [
    '/comercial/disponibilidade',
    '/gestao/dashboard',
    '/gestao/aprovacoes',
    '/gestao/relatorios',
    '/faturamento/notas-xml',
    '/admin/auditoria',
  ],
};
